### ISSUE TITLE
Update-ethereum command should take version numbers into account

### ISSUE THREAD

**Issue by Swader** [diglos/userpatches#1]
```bash
(Reading database ... 30377 files and directories currently installed.)
Preparing to unpack geth_latest_arm64.deb ...
Unpacking geth (1.8.22) over (1.8.22) ...
Preparing to unpack parity_latest_arm64.deb ...
Unpacking parity (2.2.9-0) over (2.2.8-0) ...
```

Geth could have been skipped in this case.

**Comment by diglos** [comment]
Thanks for reporting.

This script is intented as a "work around" for updating until a proper apt repo is setup. Anyway, I'll try to fix it in the next release.

**Comment by diglos** [comment]
Added --skip-same-version --refuse-downgrade options to dpkg to avoid this.
