### ISSUE TITLE
Version for Raspberry PI 4

### ISSUE THREAD

**Issue by DiegoDDT** [diglos/userpatches#10]
Raspberry PI 4 has USB 3.1 ports so I guess it's possible to connect an SSD drive with similar performances to one directly connected to PCIe. So it possible to use a Raspberry PI 4 to run a functioning ETH full node? If yes, are you going to release a version for PI 4?

Thanks

**Comment by diglos** [comment]
Hi,
The image you are looking for is on the Raspbian repository. It already supports the Raspberry Pi 4:
https://github.com/diglos/pi-gen
The image is this one:
https://ethraspbian.com/downloads/image_2019-07-25-EthRaspbian2.0-lite.zip
Although you can attach an SSD through the USB port the performance is far from a NVMe drive. You can try to sync the blockchain, of course (it may work). Please report back if you do.

**Comment by DiegoDDT** [comment]
Thanks diglos, I'm testing it. What I referred to when I asked for a version for PI 4 are the custom tweaks that you developed for  FriendlyElec NanoPC-T4 [1] and PINE RockPRO64 [5] . More specifically, the auto-mounting, partitioning and assigning of the swap memory to the SSD. Those parts of the process are not so easy to execute for a non technical person - such as me - and having it out of the box would be very helpfull. Btw, I managed to mount the SSD drive, but how to assign SWAP memory to it instead of the SD? Thanks

**Comment by diglos** [comment]
Oh, good point.
You need to look at the mount point (with the `mount` command). For example, I mount the NVMe SSD drive on /home/ethereum (it is just used for syncing the blockchain) and I place the swapfile there. This is the code [1]:
```
mkdir -p /home/ethereum/swap
dd if=/dev/zero of=/home/ethereum/swap/swapfile bs=16k count=256k
chmod 600 /home/ethereum/swap/swapfile
mkswap /home/ethereum/swap/swapfile
swapon /home/ethereum/swap/swapfile
```
If The Raspberry Pi 4 is capable of syncing the blockchain I will add this to the image, sure. Can you try to and report back here?

[1] https://github.com/diglos/userpatches/blob/master/overlay/armbian_first_run.txt

**Comment by DiegoDDT** [comment]
Cool thanks, mounting the SDD in the home folder avoids the need for specifying to geth and parity where to save the blockchain data correct?
After I input this line of code:
`dd if=/dev/zero of=/home/ethereum/swap/swapfile bs=16k count=256k`
 I had the following output:
```
ethereum@ethnode-0666e1fa:~$ dd if=/dev/zero of=/home/ethereum/swap/swapfile bs=16k count=256k
dd: error writing '/home/ethereum/swap/swapfile': File too large
262144+0 records in
262143+0 records out
4294967295 bytes (4.3 GB, 4.0 GiB) copied, 182.127 s, 23.6 MB/s

```
Is that a problem? if yes how to fix that?

**Comment by DiegoDDT** [comment]
Also with the last line of code I have the following problem:

`ethereum@ethnode-0666e1fa:~$ swapon /home/ethereum/swap/swapfile
swapon: /home/ethereum/swap/swapfile: insecure permissions 0755, 0600 suggested.
swapon: /home/ethereum/swap/swapfile: insecure file owner 1000, 0 (root) suggested.
swapon: /home/ethereum/swap/swapfile: swapon failed: Operation not permitted`

Looks like i need the root access, actually I tried to log as root but nor 'ethereum' nor '1234' password works

**Comment by heueristik** [comment]
> Hi,
> The image you are looking for is on the Raspbian repository. It already supports the Raspberry Pi 4:
> https://github.com/diglos/pi-gen
> The image is this one:
> https://ethraspbian.com/downloads/image_2019-07-25-EthRaspbian2.0-lite.zip
> Although you can attach an SSD through the USB port the performance is far from a NVMe drive. You can try to sync the blockchain, of course (it may work). Please report back if you do.

Did it work? I want to try the same with my Raspberry Pi 4B and a Samsung T5 SSD. Unfortunately, the link to the EthRaspbian2.0 image is not working anymore.

**Comment by diglos** [comment]
Hi,

The newest image is this:

https://ethraspbian.com/downloads/image_2019-12-20-EthRaspbian2.0-lite.zip

It has a 64-bit kernel so it runs fine (it may crash eventually but the node is totally functional).

Let me know if that works for you!

**Comment by DiegoDDT** [comment]
> > Hi,
> > The image you are looking for is on the Raspbian repository. It already supports the Raspberry Pi 4:
> > https://github.com/diglos/pi-gen
> > The image is this one:
> > https://ethraspbian.com/downloads/image_2019-07-25-EthRaspbian2.0-lite.zip
> > Although you can attach an SSD through the USB port the performance is far from a NVMe drive. You can try to sync the blockchain, of course (it may work). Please report back if you do.
> 
> Did it work? I want to try the same with my Raspberry Pi 4B and a Samsung T5 SSD. Unfortunately, the link to the EthRaspbian2.0 image is not working anymore.

No.. It didn't..

**Comment by DiegoDDT** [comment]
> Hi,
> 
> The newest image is this:
> 
> https://ethraspbian.com/downloads/image_2019-12-20-EthRaspbian2.0-lite.zip
> 
> It has a 64-bit kernel so it runs fine (it may crash eventually but the node is totally functional).
> 
> Let me know if that works for you!

Cool, I'll try it! What harware setup was the image tested on ?

**Comment by heueristik** [comment]
> Hi,
> 
> The newest image is this:
> 
> https://ethraspbian.com/downloads/image_2019-12-20-EthRaspbian2.0-lite.zip
> 
> It has a 64-bit kernel so it runs fine (it may crash eventually but the node is totally functional).
> 
> Let me know if that works for you!

Yes, it works nicely. Geth is syncing and writing to the SSD.
