### ISSUE TITLE
Update prysm packages on apt-repository

### ISSUE THREAD

**Issue by mangoleap** [diglos/userpatches#13]
See title. Prysmatic Labs restarted the beacon testnet. The current package is unable to sync.

https://github.com/prysmaticlabs/prysm/releases

**Comment by diglos** [comment]
Hi,

thanks for letting me know. You can update by running:

`sudo apt-get update && sudo apt-get install prysm-beacon prysm-validator`

**Comment by mangoleap** [comment]
Thanks, I think a was a little bit too early. It said it's already up to date but now it installed just fine.
