### ISSUE TITLE
1.8.23 is out with some sync fixes, might speed things up

### ISSUE THREAD

**Issue by Swader** [diglos/userpatches#5]
[New release](https://github.com/ethereum/go-ethereum/releases/tag/v1.8.23)

**Comment by diglos** [comment]
Geth and Parity updated to latest versions

**Comment by Swader** [comment]
What is the best way to update an already running node? `update-ethereum` still fetches the old one.

**Comment by diglos** [comment]
Try first running `rm -rf /tmp/*deb*` command and then `update-ethereum`

**Comment by Swader** [comment]
~~It still unpacks 1.8.22.~~ Mistyped as`deb*`, all good.
